FROM rabbitmq:4-management

# Instala ferramentas necessárias
# RUN apt-get update && apt-get install -y curl unzip

# Baixa o plugin diretamente do GitHub e ativa
# RUN curl -L -o /plugins/rabbitmq_delayed_message_exchange.ez \
# https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v4.0.2/rabbitmq_delayed_message_exchange-4.0.2.ez

# RUN rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange
